openapi: 3.0.0
info:
  title: root
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /redfish/v1/Chassis/{ChassisId}:
    get:
      parameters:
      - description: The value of the Id property of the Chassis resource
        in: path
        name: ChassisId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: http://redfish.dmtf.org/schemas/v1/Chassis.yaml#/components/schemas/Chassis
          description: The response contains a representation of the Chassis resource
components:
  schemas: {}
